# Generated by Django 5.1.2 on 2024-10-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='group',
            field=models.IntegerField(),
        ),
    ]
