# Generated by Django 5.1.2 on 2024-10-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_alter_studentmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
