# Generated by Django 5.1.2 on 2024-10-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_contact_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
