# Generated by Django 5.1.2 on 2024-11-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
