# Generated by Django 5.1.2 on 2024-11-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_image_id_alter_text_id_alter_text_photo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='id',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='id',
            new_name='num',
        ),
    ]
