# Generated by Django 5.1.5 on 2025-02-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddbookModel',
            fields=[
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('student_roll', models.CharField(max_length=50, unique=True)),
                ('deparment', models.CharField(max_length=100)),
                ('sub_name', models.CharField(max_length=100)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
