# Generated by Django 5.1.5 on 2025-02-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libaray_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbookmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
