# Generated by Django 5.1.5 on 2025-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libaray_app', '0002_addbookmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
                ('img', models.ImageField(upload_to='profile_img')),
            ],
        ),
    ]
