# Generated by Django 5.1.1 on 2024-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Physicas', 'physics'), ('Bangla', 'Bangla'), ('English', 'English'), ('Math', 'Math'), ('Polictis', 'Polictis'), ('Science', 'Science')], max_length=30)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField()),
            ],
        ),
    ]
